### ISSUE TITLE
Support for ingress-bandwidth and egress-bandwidth?

### ISSUE THREAD

**Issue by zoobab** [Pharb/kubernetes-iperf3#1]
Hi,

I am trying to add values for ingress-bandwidth and egress-bandwidth:

```
  template:
    metadata:
      labels:
        app: iperf3-server
        kubernetes.io/ingress-bandwidth: 1M
        kubernetes.io/egress-bandwidth: 1M
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
```

But that does not seem to have an effect on the throughput speed, any idea?
