### ISSUE TITLE
How to measure UDP?

### ISSUE THREAD

**Issue by saireddyavs** [Pharb/kubernetes-iperf3#2]
By default you're using TCP..I also  want to find the performance on UDP.

I have tried by changing protocol name from TCP to UDP in **iperf3.yml** , and also added **./iperf3.sh -t 10 -u** for UDP support
but getting timeout...TCP worked fine..
```
kubernetes-iperf3$ ./iperf3.sh -t 10 -u
deployment.apps/iperf3-server-deployment created
service/iperf3-server created
daemonset.apps/iperf3-clients created
Waiting for iperf3 server to start...
Waiting for iperf3 server to start...
Server is running

iperf3: error - unable to connect to server: Connection timed out
command terminated with exit code 1
```

also tried adding ```kubectl exec -it ${POD} -- iperf3 -u -c iperf3-server -T "Client on ${HOST}" $@``` in run.sh

**Comment by Pharb** [comment]
Thanks for the question @saireddyavs.

I have not tried it, but I guess the following three points need to be changed for UPD measurement:
- iperf3 server
- iperf3 client
- service protocol

You mentioned that you added the `-u` flag for the client and changed the service protocol from TCP to UDP.
I guess you should also try to add the `-u` flag to the server to accept incoming UDP traffic:

```
      - name: iperf3-server
        image: networkstatic/iperf3
        args: ['-s -u']
```
(https://github.com/Pharb/kubernetes-iperf3/blob/master/iperf3.yaml#L34)

**Comment by Orabig** [comment]
No, args: ['-s -u'] doesn't work, because -u is a client-only argument.

I don't have the issue if I try to connect manually in some client node and run iperf3 on the POD's ip instead of service's one.

```
root@iperf3-clients-n5lrg:/# iperf3 -c 192.168.4.49 -u -t 1
Connecting to host 192.168.4.49, port 5201
[  5] local 192.168.3.29 port 59682 connected to 192.168.4.49 port 5201
[ ID] Interval           Transfer     Bitrate         Total Datagrams
[  5]   0.00-1.00   sec   128 KBytes  1.05 Mbits/sec  94
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec   128 KBytes  1.05 Mbits/sec  0.000 ms  0/94 (0%)  sender
[  5]   0.00-1.04   sec   128 KBytes  1.01 Mbits/sec  0.008 ms  0/94 (0%)  receiver

iperf Done.
root@iperf3-clients-n5lrg:/# iperf3 -c iperf3-server -u -t 1
iperf3: error - unable to connect to server: Connection timed out
```

**Comment by Pharb** [comment]
> if I try to connect manually in some client node and run iperf3 on the POD's ip instead of service's one.

Are you sure you changed the service protocol to UDP as mentioned above? (see this line: https://github.com/Pharb/kubernetes-iperf3/blob/5a86d7cabe630a21a9c99dcb0edc0d9c54f8af61/iperf3.yaml#L50)

**Comment by piotrekz79** [comment]
this worked for me

```
      containers:
      - name: iperf3-server
        image: networkstatic/iperf3
        args: ['-s']
        ports:
        - containerPort: 5201
          name: server-udp
          protocol: UDP
        - containerPort: 5201
          name: server-tcp
          protocol: TCP

```

and in service

```
  ports:
  - protocol: TCP
    port: 5201
    targetPort: server-tcp
    name: svc-server-tcp
  - protocol: UDP
    port: 5201
    targetPort: server-udp
    name: svc-server-udp
```
